# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Regrex.it
email: regrexit@hactar.is
description: > # this means to ignore newlines until "baseurl:"
  A collection of resources for helping to ensure a safe future for the UK.
  Got a resource that you think we should add? Email or tweet us to let us know.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://regrex.it" # the base hostname & protocol for your site
twitter_username: regrex_it
github_username:  hactar

# Build settings
markdown: kramdown

collections:
  - links

exclude:
  - fabfile.py
  - fabfile.pyc
